import {describe,it,expect} from 'vitest';
import {parseBillingCommand,verifyPayMongoSignature,normalizeGoogleSubscription,normalizeAppleSubscription,safeCheckoutUrl,productCatalog} from './billingProtocol.ts';
const catalog=productCatalog(JSON.stringify([{provider:'google',id:'fixture-plus',basePlan:'monthly',tier:'plus',interval:'monthly'},{provider:'apple',id:'fixture-pro',tier:'pro',interval:'annual'}]));
// All identifiers, amounts, receipt objects and signatures in this file are deterministic test data.
describe('billing boundary',()=>{
 it('rejects client entitlement/price/owner injection',()=>{for(const v of [{action:'web_checkout',tier:'pro',interval:'monthly',amount:1},{action:'verify_google',token:'x',user_id:'victim'},{action:'status',tier:'pro'}])expect(()=>parseBillingCommand(v)).toThrow();});
 it('accepts only bounded receipt references',()=>{expect(parseBillingCommand({action:'verify_google',token:'fixture-token'})).toEqual({action:'verify_google',token:'fixture-token'});expect(()=>parseBillingCommand({action:'verify_google',token:'a'.repeat(3000)})).toThrow();});
 it('has no checkout redirects to arbitrary or insecure hosts',()=>{expect(safeCheckoutUrl('https://payments.paymaya.com/fixture')).toBeTruthy();for(const url of ['http://payments.paymaya.com','https://payments.paymaya.com.evil.test','https://user@payments.paymaya.com','https://127.0.0.1'])expect(safeCheckoutUrl(url)).toBeNull();});
 it('verifies the raw signed body, mode and fresh timestamp',async()=>{const raw='{"fixture":true}',secret='test-data-only',now=1800000000000,t=String(now/1000);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${t}.${raw}`));const hex=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');expect(await verifyPayMongoSignature(raw,`t=${t},te=${hex}`,secret,false,now)).toBe(true);for(const [body,header,date] of [[raw+' ',`t=${t},te=${hex}`,now],[raw,`t=${t},li=${hex}`,now],[raw,`t=${t},te=${hex}`,now+301000]])expect(await verifyPayMongoSignature(String(body),String(header),secret,false,Number(date))).toBe(false);});
 it('cannot grant from unknown product, wrong owner, expired or suspended Google state',()=>{const data={startTime:'2026-09-01T00:00:00Z',subscriptionState:'SUBSCRIPTION_STATE_ACTIVE',externalAccountIdentifiers:{obfuscatedExternalAccountId:'owner-hash'},lineItems:[{productId:'fixture-plus',expiryTime:'2026-10-01T00:00:00Z',offerDetails:{basePlanId:'monthly'},autoRenewingPlan:{autoRenewEnabled:true}}]};expect(normalizeGoogleSubscription(data,'owner-hash','hash',catalog).tier).toBe('plus');expect(()=>normalizeGoogleSubscription(data,'wrong','hash',catalog)).toThrow();expect(normalizeGoogleSubscription({...data,subscriptionState:'SUBSCRIPTION_STATE_ON_HOLD'},'owner-hash','hash',catalog).status).toBe('expired');expect(()=>normalizeGoogleSubscription({...data,lineItems:[{...data.lineItems[0],productId:'unknown'}]},'owner-hash','hash',catalog)).toThrow();});
 it('Apple requires a verified account-bound transaction and treats revocation as revoked',()=>{const tx={appAccountToken:'owner',originalTransactionId:'fixture-transaction',transactionId:'fixture-renewal',productId:'fixture-pro',purchaseDate:1800000000000,expiresDate:1801000000000,type:'Auto-Renewable Subscription'};expect(normalizeAppleSubscription(tx,{autoRenewStatus:1},'owner',catalog).tier).toBe('pro');expect(()=>normalizeAppleSubscription(tx,{},'victim',catalog)).toThrow();expect(normalizeAppleSubscription({...tx,revocationDate:1800000100000},{},'owner',catalog).status).toBe('revoked');});
});
