// src/styles/auth.ts
import { StyleSheet } from "react-native";
import { Colors } from "./colors";

export const AuthStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.primary,
  },
  formContainer: {
    width: "100%",
    maxWidth: 420,
    padding: 32,
    borderRadius: 28,
    backgroundColor: Colors.secondary,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 32,
    elevation: 16,
  },
  label: {
    marginBottom: 7,
    fontWeight: "700",
    color: Colors.textSecondary,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  inputContainer: {
    marginBottom: 18,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.borderLight,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: Colors.inputBg,
    color: Colors.text,
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonContainer: {
    marginTop: 6,
    gap: 12,
  },
  primaryBtn: {
    backgroundColor: Colors.accent,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  primaryBtnText: {
    color: Colors.textOnAccent,
    fontWeight: "800",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  toggleContainer: {
    marginTop: 20,
    alignItems: "center",
  },
  toggleText: {
    color: Colors.textMuted,
    fontSize: 14,
  },
  toggleTextBold: {
    color: Colors.accent,
    fontWeight: "700",
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    maxWidth: 340,
    backgroundColor: Colors.secondary,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    elevation: 20,
  },
  modalTitle: {
    color: Colors.accent,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
    textAlign: "center",
  },
  modalMessage: {
    color: Colors.textSecondary,
    fontSize: 14,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButton: {
    backgroundColor: Colors.accent,
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 12,
    width: "100%",
  },
  modalButtonText: {
    color: Colors.textOnAccent,
    fontWeight: "800",
    fontSize: 15,
    textAlign: "center",
  },
});
