// src/styles/auth.ts
import { StyleSheet } from "react-native";
import { Colors } from "./colors";

export const AuthStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.primary,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
  },
  webScrollContent: {
    paddingHorizontal: 48,
    paddingVertical: 32,
  },
  webAuthShell: {
    width: "100%",
    maxWidth: 1080,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 56,
  },
  webBrandPanel: {
    flex: 1,
    minWidth: 0,
  },
  webBrandMark: {
    width: 108,
    height: 108,
    borderRadius: 30,
    backgroundColor: Colors.secondary,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 28,
  },
  webBrandLogo: {
    width: 76,
    height: 76,
  },
  webBrandTitle: {
    color: Colors.text,
    fontSize: 50,
    fontWeight: "900",
    lineHeight: 56,
    marginBottom: 14,
  },
  webBrandCopy: {
    color: Colors.textSecondary,
    fontSize: 18,
    lineHeight: 28,
    maxWidth: 460,
  },
  webBrandStats: {
    flexDirection: "row",
    gap: 12,
    marginTop: 34,
  },
  webBrandStat: {
    minWidth: 128,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    borderRadius: 18,
    backgroundColor: Colors.secondary,
  },
  webBrandStatValue: {
    color: Colors.accent,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 4,
  },
  webBrandStatLabel: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  webFormSlot: {
    width: 440,
    flexShrink: 0,
  },
  formContainer: {
    width: "100%",
    maxWidth: 420,
    padding: 32,
    borderRadius: 28,
    backgroundColor: Colors.secondary,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 32,
    elevation: 16,
  },
  authFormContainer: {
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  webAuthFormContainer: {
    maxWidth: 440,
  },
  webStatsContainer: {
    maxWidth: 900,
    paddingHorizontal: 34,
  },
  webActivityGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  webActivityOption: {
    flexBasis: "23%",
    flexGrow: 1,
    minWidth: 176,
  },
  webGoalOption: {
    flexBasis: "18%",
    minWidth: 130,
  },
  unitSection: {
    marginBottom: 16,
  },
  statValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 3,
    minWidth: 0,
  },
  statValueInput: {
    flex: 1,
    minWidth: 0,
    color: Colors.text,
    fontSize: 28,
    fontWeight: "900",
    padding: 0,
  },
  statUnitText: {
    color: Colors.textMuted,
    flexShrink: 0,
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  imperialHeightRow: {
    flexDirection: "row",
    gap: 12,
  },
  imperialHeightField: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 3,
  },
  minorNotice: {
    padding: 16,
    marginBottom: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.inputBg,
  },
  minorNoticeTitle: {
    color: Colors.accent,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 6,
  },
  minorNoticeText: {
    color: Colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  calculatorNotice: {
    color: Colors.textMuted,
    fontSize: 11,
    lineHeight: 17,
    marginBottom: 18,
  },
  targetBreakdownSection: {
    marginBottom: 32,
  },
  authInputIcon: {
    width: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  label: {
    marginBottom: 7,
    fontWeight: "700",
    color: Colors.textSecondary,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  inputContainer: {
    marginBottom: 18,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.borderLight,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: Colors.inputBg,
    color: Colors.text,
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonContainer: {
    marginTop: 6,
    gap: 12,
  },
  primaryBtn: {
    backgroundColor: Colors.accent,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  primaryBtnText: {
    color: Colors.textOnAccent,
    fontWeight: "800",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  toggleContainer: {
    marginTop: 20,
    alignItems: "center",
  },
  toggleText: {
    color: Colors.textMuted,
    fontSize: 14,
  },
  toggleTextBold: {
    color: Colors.accent,
    fontWeight: "700",
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    maxWidth: 340,
    backgroundColor: Colors.secondary,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.borderLight,
    shadowColor: Colors.accent,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    elevation: 20,
  },
  modalTitle: {
    color: Colors.accent,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
    textAlign: "center",
  },
  modalMessage: {
    color: Colors.textSecondary,
    fontSize: 14,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButton: {
    backgroundColor: Colors.accent,
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 12,
    width: "100%",
  },
  modalButtonText: {
    color: Colors.textOnAccent,
    fontWeight: "800",
    fontSize: 15,
    textAlign: "center",
  },
});
