import { LegalPage } from "@/src/components/legal/LegalPage";

export default function PrivacyRoute() {
  return <LegalPage title="Privacy policy" intro="Your diary, body measurements, and Bee preferences belong to your account. This page explains the data used by the current TrackBing implementation." sections={[
    { heading: "Account, goals, and food diary", paragraphs: [
      "Supabase Auth processes your email, password credentials, verification codes, and session information. TrackBing stores your age, gender selection, height, current and target weight, recorded weight history, activity level, nutrition goals, logged foods, serving sizes, diary dates, personal foods, and recipes in Supabase when you enter them.",
      "These records are private to your account through database access policies. Nutrition calculations use the measurements and goals you choose. When private dashboard insights are enabled, today's aggregate intake and goals, recent dated weight records, and relevant explicit preferences may be processed by Gemini through the server to produce suggestions for your account. That insight branch does not enable Google Search. Generated insight text may be kept privately for up to a day to avoid repeating the same work, and refreshed when the relevant data or day changes. These suggestions are not medical advice and are not a shared food database. They are estimates, not diagnoses. Saved diary entries and goals remain until you edit or delete them; account-wide deletion and backup retention need an operator-supported process and are not currently an in-app promise.",
    ] },
    { heading: "Subscriptions and payment providers", paragraphs: [
      "Basic manual tracking stays free. Paid Plus/Pro subscriptions belong to your account across devices. When configured, web payment details are entered in Maya's provider flow through PayMongo; iOS and Android purchases use Apple and Google Play. TrackBing does not collect card numbers or wallet passwords. Providers process the billing information needed for purchases under their own policies.",
      "TrackBing stores verified provider subscription/product/transaction identifiers, paid periods, renewal/status events, account bindings, and numeric AI allowances privately. Play purchase tokens and web billing customer/payment identifiers are server-only verification data. Billing records, backups, refund handling and account erasure retention still need the real operator's review. Cancelling renewal does not delete your diary or already-paid access unless the provider revokes that purchase.",
    ] },
    { heading: "Barcode, camera, and food searches", paragraphs: [
      "Camera permission is optional and used to decode food barcodes on your device. The current scanner does not upload camera frames or package photos to Bee. You can type a barcode or enter a food label manually instead. Photo-based nutrition reading is not currently implemented.",
      "Barcode and product searches may send the barcode or food search term to Open Food Facts. USDA FoodData Central searches run through the authenticated server proxy; food queries are sent to USDA. The app also downloads its existing public Filipino-food list from GitHub. These services receive the network information needed to answer requests. Open Food Facts is a public food database, not a place to submit your private diary.",
    ] },
    { heading: "Bee chat, Gemini, and live Google Search", paragraphs: [
      "Bee sends your message and a small relevant context to Gemini through a server-only API key. Context can include the food under discussion, explicit saved preferences, and a bounded recent conversation. It does not send months of your diary to Google Search. Food-history questions read your real account records.",
      "Google Search is enabled only for a live search branch when an independently usable food record cannot resolve your request, or when you explicitly request a web search. The product query is sent to Google. Search answers, citations, and Search Suggestions are displayed only in the active answer and are not stored in TrackBing's database, replay records, shared food index, or reusable cache.",
      "Gemini requests set store:false, so TrackBing does not rely on Interactions conversation storage. This does not remove Google's separate service processing, safety logging, or grounding retention. Google's published grounding handling can retain search-related information for 30 days. The operator must confirm the paid-service billing configuration and current Google data-use terms before launch; unpaid and paid service data-use rules can differ.",
      "Normal Bee conversation content is stored privately for up to 30 days and at most 50 messages per thread, with server pruning. Clear chat removes conversation content, and a new conversation starts separately. Neither operation deletes your food diary. Verified independent nutrition provenance stays with a confirmed diary entry. Numeric usage counts help enforce quotas without logging your prompt body.",
    ] },
    { heading: "Saved preferences and your controls", paragraphs: [
      "Bee saves durable preferences only when you explicitly ask or use Saved preferences. Permitted facts include your preferred name, units, usual product, and usual preparation. It does not infer diagnoses or permanent health facts from an ordinary food question.",
      "Open Bee's Saved preferences to see, edit, delete, or clear these values. Deleted preferences are not recreated from an old assistant summary. Preferences stay until you edit or delete them. You can separately clear your chat; confirmed food history remains authoritative.",
    ] },
    { heading: "Device storage, hosting, and optional measurement", paragraphs: [
      "Essential sign-in/session data is kept in browser local storage on web and app storage on mobile. Local cached diary and goal data makes repeat visits faster. Sign-out and account switching protect which account is shown, but local device storage should still be treated as sensitive; use a trusted device.",
      "Your browser stores an accepted/declined analytics choice under trackbing.analytics-consent.v1. Decline or revoke optional analytics in Profile to stop further requests. Do Not Track and Global Privacy Control are respected. Essential authentication does not depend on optional consent. The web app is configured for Vercel hosting. Supabase, hosting providers, and food APIs may process IP addresses and operational request logs to run their services. TrackBing does not put Gemini, USDA, or Supabase service-role keys in the client.",
      "Optional web analytics is off by default. When the operator enables Plausible, an accept/decline choice appears before optional requests. It records only fixed page names and aggregate sign-in/sign-up events, without food text, Bee prompts, barcode parameters, emails, user IDs, body measurements, or referrers. Plausible still processes the network IP address and User-Agent needed to receive a request under its own data policy. The operator must approve its account, retention, and data handling before enabling it. No optional native analytics is implemented.",
    ] },
    { heading: "Retention, deletion, and operator review", paragraphs: [
      "Chat and preference controls above are implemented in the app. Diary entries, personal foods, and recipes have their own edit/delete controls. A complete account-deletion contact/process, database backup retention, hosting-log retention, legal basis, regional processing, age eligibility, and user-rights procedure require the real operator's review. This draft does not imply those decisions have been approved.",
      "Do not place another person's private information, passwords, or payment details in Bee. External food records and AI answers can be wrong; you decide whether to save a reviewed serving.",
    ] },
  ]} />;
}
